project: 
  type: website

website: 
  page-navigation: true
  title: "NOAA quarto simple" 
  site-url: "https://nmfs-opensci.github.io/NOAA-quarto-simple" 
  repo-url: "https://github.com/nmfs-opensci/NOAA-quarto-simple"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    logo: images/nmfs.png
    # favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.fisheries.noaa.gov/
        text: "National Marine Fisheries Service"
      - icon: github
        href: https://github.com/nmfs-opensci
        text: "GitHub"

    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: "Introduction"
      - href: content/qualtrics.qmd
        text: "About Qualtrics"
      - section: content/survey.qmd
        text: "Survey Overview"
        contents:
          - content/survey-building.qmd
          - content/survey-distributing.qmd
          - content/survey-maintaining.qmd
      - href: content/contact.qmd
        text: "Contact"


format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
